module.exports = {
  crawlerOptions: {
    basicCrawler: {
      keepAlive: true,
      maxConcurrency: 50,
      maxRequestRetries: 0,
      maxRequestsPerCrawl: 0,
      maxRequestsPerMinute: 70,
      minConcurrency: 1,
      requestHandlerTimeoutSecs: 60,
    },
    cheerioCrawler: {
      keepAlive: true,
      maxConcurrency: 50,
      maxRequestRetries: 0,
      maxRequestsPerCrawl: 0,
      maxRequestsPerMinute: 70,
      minConcurrency: 1,
      requestHandlerTimeoutSecs: 60,
    },
    httpCrawler: {},
    jsdomCrawler: {
      hideInternalConsole: false,
      keepAlive: true,
      maxConcurrency: 50,
      maxRequestRetries: 0,
      maxRequestsPerCrawl: 0,
      maxRequestsPerMinute: 70,
      minConcurrency: 1,
      navigationTimeoutSecs: 60,
      requestHandlerTimeoutSecs: 60,
      runScripts: true,
    },
    playwrightCrawler: {},
    puppeteerCrawler: {
      headless: false,
      keepAlive: true,
      maxConcurrency: 3,
      maxRequestRetries: 0,
      maxRequestsPerCrawl: 0,
      maxRequestsPerMinute: 30,
      minConcurrency: 1,
      navigationTimeoutSecs: 90,
      requestHandlerTimeoutSecs: 90,
    },
  },
  environment_variable_config: `${__dirname}/.env`,
  minimalArgsForBrowserCrawler: [],
};
